### ISSUE TITLE
Any plans to upload to opam?

### ISSUE THREAD

**Issue by dylanirlbeck** [flowtype/ocaml-ppx_gen_rec#4]
I'd love to install this PPX locally for one of my projects, but I don't see any installation instructions in the `README`. Are there any plans to publish this ppx to opam (or make it part of `ppx.deriving`)?

Thanks in advance!

**Comment by mroch** [comment]
http://opam.ocaml.org/packages/ppx_gen_rec/

for the just-released 2.0.0: https://github.com/ocaml/opam-repository/pull/18643
